# Generated by Django 4.2 on 2024-10-18 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conference_options_alter_conference_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conference',
            name='the start date must be greater than today or equal',
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2024, 10, 18))), name='start_date_must_be_today_or_future'),
        ),
    ]
