# Generated by Django 4.2 on 2024-10-19 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_remove_conference_the_start_date_must_be_greater_than_today_or_equal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conference',
            name='start_date_must_be_today_or_future',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='conference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 10, 19)),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2024, 10, 19))), name='the start date must be greater than today or equal'),
        ),
    ]
